# Generated by Django 5.1.1 on 2025-08-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messess',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('specialties', models.JSONField(default=list)),
                ('openingHours', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recommended', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('tags', models.JSONField(default=list)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messes', to='accounts.messowner')),
            ],
        ),
    ]
